### ISSUE TITLE
Getting description two times

### ISSUE THREAD

**Issue by Logan1x** [wayou/hexo-image-caption#2]
`![login](css/images/terminal.png "login window")` used this code to generate description for image but getting like this 

![screenshot-2017-12-8 blag](https://user-images.githubusercontent.com/10944610/33766956-ca4a64ee-dc45-11e7-92ef-db853fe0c24c.png)

**Comment by wayou** [comment]
A working demo that I can inspect on?

**Comment by Logan1x** [comment]
the issue has been solved @wayou thanks for asking.
